# Generated by Django 5.0.2 on 2025-06-06 09:47

import froala_editor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='featured/')),
                ('content', froala_editor.fields.FroalaField()),
                ('meta_description', models.TextField(max_length=250)),
                ('slug', models.SlugField(blank=True, max_length=300, null=True, unique=True)),
            ],
        ),
    ]
