# Generated by Django 5.0.2 on 2025-06-07 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviehouse', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pp',
            field=models.ImageField(blank=True, null=True, upload_to='pp/'),
        ),
    ]
